### ISSUE TITLE
Request for Instructions on How to Feed a binary file to the simulator

### ISSUE THREAD

**Issue by piyumalranawaka** [RRZE-HPC/pycachesim#12]
Hi,

I find your simulator very interesting for my research. I am trying to figure out how to feed a workload into the simulator but unfortunately I could not find any information.I would be much thankful if you could provide some instructions on how to do it.

Thank You &
Warm Regards,
Piyumal

**Comment by cod3monk** [comment]
This requires some little programming. An example is given in https://github.com/RRZE-HPC/pycachesim/blob/master/examples.py

On line 37 you see how a single byte is loaded from address 23.

For performance reasons I suggest using the `load`, `store` and `loadstore` (found in the `CacheSimulator` class) functions with iterators that give a sequence of addresses instead of accessing single addresses.

Hope this helps as a starting point.

**Comment by cod3monk** [comment]
Feel free to reopen if more questions come up.
